version: '3.8'
# run this command in terminal before running docker 'xhost +local:docker'
services:
  conference-app:
    build: .
    volumes:
      - ./app:/app
      - conference-data:/data
    environment:
      - DISPLAY=\${DISPLAY}
      - XAUTHORITY=~/.Xauthority
    network_mode: host
    tty: true

volumes:
  conference-data:
